<?php
/** @var Attributes $block */
?>
<div class='product-description'>

    <ul>
    <?php foreach ($block->getThreeAttributes() as $a): ?>
        <li>
            <b>
                <?= $a['value']; ?>:
            </b>
                <?= $a['label']; ?>
        </li>
    <?php endforeach; ?>
    </ul>



    <div class='short-description'>
        <?php
        echo $block->description->getProduct()->getShortDescription();
        ?>
    </div>
</div>

