<?php if ($pages = $block->getPages()): ?>
    <?php if ($title = $block->getData('widgettitle')): ?>
        <h2><?= $title; ?></h2>
    <?php endif ?>
    <ul>
        <?php foreach ($pages as $page): ?>
            <li>
                <a href="<?= $block->getUrl($page->getIdentifier()); ?>">
                    <?= $page->getTitle(); ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
